### PR TITLE
Added comments to code

### PR DESCRIPTION
**Pull request by erinwalker**
Hey Dom, I added comments to the achievement system code. Let me know if it is alright.

### CODE REVIEW

**Comment by DomAmato** [comment]
You have merge conflicts can you fix them. Its in the Requirements.java at line 524-560. For some reason it is saying those are conflicts though I dont see why. Also the event handler file says its totally out of sync

**Comment by erinwalker** [comment]
Hey check it now, I think I got rid of the conflicts.

**Comment by DomAmato** [comment]
looks good to me

**Comment by erinwalker** [comment]
Sweet!

**Pull request merged**
